# Generated by Django 5.2.1 on 2025-05-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="category",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                ],
                max_length=10,
            ),
        ),
    ]
