# Generated by Django 5.2.1 on 2025-06-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="category",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher"), ("hr", "HR")],
                max_length=10,
            ),
        ),
    ]
