# Generated by Django 5.2.1 on 2025-05-31 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="assigned_teachers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"category": "Teacher"},
                related_name="assigned_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
